Шедевро Кложур. Линейная Алгебра, опять.
YuMSh-Ivanov/clojure-linear-IlDen01 pull request #2
Opened 2024-11-17 15:14 UTC by IlDen01

2024-11-17 15:16 UTC, pure-vessel requested changes

2024-11-17 15:16 UTC, pure-vessel commented on src/linear.clj
> +            (mapv #(mapv (partial dot %) (transpose next)) res))
Где-то я `#(mapv (partial dot %) ...)` уже видел...

2024-11-17 16:32 UTC, IlDen01 commented on src/linear.clj
> +            (mapv #(mapv (partial dot %) (transpose next)) res))
Fixoed

2024-11-17 18:53 UTC, IlDen01 commented on src/linear.clj
> +            (mapv #(mapv (partial dot %) (transpose next)) res))
Fixoed.
Зачем мучаться и выносить копипасту (я с этим так и не справиля, честно стралася ее вынести с момента Вашего комментария), если можно переписать функцию! Круто же?

2024-11-26 09:03 UTC, pure-vessel approved these changes

2025-11-21 15:26 UTC, closed without merging